### ISSUE TITLE
E27 record unindexed without warning or reason

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#111]
A site record (E27), after having been edited and saved fine without any error warning, was subsequently not indexed anymore. There did not appear to be a reason for the un-indexing of the record. It seems important to flag up though, as we don't want sites to disappear from the database without warning...

The record in question is IDIHA-0007376 with arches ID fe3ff5ee-1dac-42a0-b989-be4e35d75270.

**Comment by pascalflohr** [comment]
This was in the Al Ula database, but might be an issue in any v2 version of the database.

**Comment by mradamcox** [comment]
@pascalflohr I just reindexed everything and then double-checked this resource and it seems to have indexed just fine.

We'll see if it disappears again! I'm not really sure what could have caused this. In some cases if a bad values is entered for a resource that is not caught by validation the indexing can fail and the resource could be "lost" until some measure is taken to retrieve it... doesn't sound like this is what happened in this case though.

**Comment by pascalflohr** [comment]
Thanks @mradamcox ! Yes, we will just have to wait and see if something like this happens again...
