### ISSUE TITLE
Bulk upload imagery attachments not visible

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#113]
When attaching images to a bulk upload of Information Resources, they seem to get loaded but are not visible in the record. In the record view, nothing is visible (in some instances there was a broken image symbol). In the edit view, the following is visible:

![Screen Shot 2019-03-26 at 13 34 22](https://user-images.githubusercontent.com/43570914/55001231-0d812180-4fcc-11e9-87dc-74286792ab8c.png)

When clicking on the arrow:

![Screen Shot 2019-03-26 at 13 34 35](https://user-images.githubusercontent.com/43570914/55001240-14a82f80-4fcc-11e9-846a-24915a9100cb.png)

This problem only occurs when bulk uploading images, not when they are loaded directly in the database one by one.

The problem occurs in all v2 instances (EAMENA, IDIHA/Al Ula).

**Comment by pascalflohr** [comment]
This has now improved, as the images are visible in the "other upload" tab in edit mode, but they do not show up in the information record screen (at least not in the Al Ula instance). They should be visible in both, with the information record screen image very important as that is where most people will need to see it.

When images are manually added to a record, they are visible in the information record view.

**Comment by pascalflohr** [comment]
Or is it possible this has something to do with how the bulk upload was structured @TeriForey ?

**Comment by pascalflohr** [comment]
One more remark: currently it is case sensitive, so if the file is called AU03000.JPG, but in the bulk upload spreadsheet it is called AU03000.jpg, the image will not be linked/loaded. If possible, it would be good to have this non-case sensitive, for ease of use.

**Comment by pascalflohr** [comment]
@mradamcox do you have an idea? I think @michaeltfisher and @TeriForey might both be away

**Comment by michaeltfisher** [comment]
@mradamcox, @TeriForey : following the May 7th commits to the AlUla-Stable branch (including PR #131), all Resource types can validate successfully during a bulk upload, but Information Resource uploads won't accept file attachments. This plays out slightly differently depending on the file(?), it seems, but in all cases the expected result is not achieved.

![Screen Shot 2019-05-09 at 14 34 27](https://user-images.githubusercontent.com/41090686/57457841-2f76f080-7268-11e9-97c7-b5cc2f50c8be.png)


<img width="917" alt="Screen Shot 2019-05-09 at 2 30 23 PM" src="https://user-images.githubusercontent.com/41090686/57457671-dad37580-7267-11e9-81af-0163b53ca5bd.png">


<img width="983" alt="Screen Shot 2019-05-09 at 2 36 59 PM" src="https://user-images.githubusercontent.com/41090686/57457716-f2126300-7267-11e9-96c7-d4c036954b71.png">

**Comment by mradamcox** [comment]
@michaeltfisher Al Ula is now, post May-7th, on the `eamena-core-arches3` branch, so the `alula-stable` branch is deprecated.
Are you able to provide an example file that didn't work on upload? I did try it from my end with the 10 Aden infor resources and that worked, but I'll try again now.

**Comment by michaeltfisher** [comment]
Yeah, I just tested it again with a new batch and it works perfectly. Not sure what the difference would be (other than human error), but we'll monitor it and see if anything jumps out going forward. Until then, case closed. Thank you @mradamcox
