### ISSUE TITLE
Restructure E24 Modification form

### ISSUE THREAD

**Issue by mradamcox** [azerbini/eamena_dev#12]
The E24 Modification form needs to be altered to look like this:

+ Type of Modification (Modification_Type.E55) & Date of Modification (Modification_Date.E49)
+ Modification Remarks (Modification_Description.E62) 
+ Construction Material (Construction_Material.E57) & Construction Technique (Construction_Technique_Type.E55) & Note (Construction_Note.E62) 

Waiting to hear the resolution to #10 as I anticipate the same issue could occur with this form.

**Comment by AzadehVafadari** [comment]
Hello both,

The way I had envisaged the Modification and Construction section to look like is to have three add groups/subsections: 1. Type and Date of Modification 2. Modification Remarks and 3. Construction Material, Technique and Note
Let me know if there's any problem with this and whether graph/form need to be modified...

**Comment by azerbini** [comment]
No @AzadehVafadari, there shouldn't be any problem. @mradamcox, you can go ahead as planned for this form, whilst the Archaeological assessment form on the E24 should be all grouped into one 'Add'. 
Thanks to both, a.

**Comment by mradamcox** [comment]
@AzadehVafadari, to clarify, each of these add groups are meant to be completely independent of each other? As far as I can tell, with the structure you have outlined one would be able to add (for example) multiple type/date groups as well as multiple modification remarks. However, the remarks would not be tied to any specific type/date group. The same goes for Construction Material, Technique, and Note... you would not be able to associate any of these with a specific modification type/date. @azerbini am I misunderstanding how this branching would work?

**Comment by azerbini** [comment]
Adam, your interpretation is correct: each instance of each group would be independent from each other.


Sent from my iPhone

On 2 May 2018, at 19:42, mradamcox <notifications@github.com<mailto:notifications@github.com>> wrote:


@AzadehVafadari<https://github.com/AzadehVafadari>, to clarify, each of these add groups are meant to be completely independent of each other? As far as I can tell, with the structure you have outlined one would be able to add (for example) multiple type/date groups as well as multiple modification remarks. However, the remarks would not be tied to any specific type/date group. @azerbini<https://github.com/azerbini> am I misunderstanding how this branching would work?

**Comment by mradamcox** [comment]
ok, thanks!

**Comment by AzadehVafadari** [comment]
Hi Adam, as Andrea said, each of the groups are independent. Remarks are general remarks/notes about any modifications (not for each added ones); Construction Materiel, Technique, and Note are also independent.

**Comment by mradamcox** [comment]
This should be resolved, but can remain open until the datetime_to_date_nodes() comment here https://github.com/azerbini/eamena_dev/pull/14 is addressed.

**Comment by azerbini** [comment]
Addressed here c07022a228c588e40684838f2994f940599823e6
