### ISSUE TITLE
Al Ula bulk upload process won't write .arches file

### ISSUE THREAD

**Issue by michaeltfisher** [azerbini/eamena_dev#129]
Al Ula users are having trouble using the bulk upload page, especially following commit 50eb432cb32a0244133cf22b7ffaf14e4a50d684. After pushing that commit, Information Resource and Relations uploads stopped working. After reverting the commit, Relations uploads would validate, but Heritage Place and Heritage Feature uploads stopped working.

The point of error seems to generally be during the .arches file writing step, after the file has passed all of the other validation steps. 

<img width="1100" alt="Screen Shot 2019-05-06 at 9 01 03 AM" src="https://user-images.githubusercontent.com/41090686/57230243-84eb9d00-6fdd-11e9-82b0-89aed0280ef0.png">

**Comment by mradamcox** [comment]
Ok, there are a few things going on here. First, indeed the extra .arches file validation did not play well with the relations loading, but that was an easy thing to fix.

Second, I found that in the Al Ula database there was somehow a missing EntityTypes object, PROJECTION_TYPE_AUTHORITY_DOCUMENT.E32. I don't understand how, but it was deleted at some point, and this was causing an error when I tried to load in an information resource spreadsheet example that I had. I don't think that was the whole problem with information resources though.

@TeriForey has had a PR out for a while that is directly related to information resources file uploads, so I'd like to get that merged in before going any further with that aspect of this ticket.

**Comment by mradamcox** [comment]
@pascalflohr can you test these problems out and see what works and what doesn't? After doing a good deal of maintenance and under-the-hood reconfigurations, both information resources and relations loaded for me.

**Comment by pascalflohr** [comment]
@mradamcox thank you for looking into this. At the moment I am not getting beyond step 1. I click on attach file, attach a file, which appears to load, but subsequently I cannot click on step 2:

![Screenshot 2019-05-07 at 10 18 26](https://user-images.githubusercontent.com/43570914/57288595-ad44cb80-70b1-11e9-8d00-51b6066d526d.png)

In this case I was attaching a E24 upload, but I don't think it matters at this stage.

**Comment by mradamcox** [comment]
@pascalflohr  Ah ok I see, I had reconfigured some things on the server and there was a lingering permissions issue. It should work fine now. Thanks for testing.

**Comment by mradamcox** [comment]
In this case you must have been trying to upload a file that you had uploaded in the past, and it was failing because it didn't have sufficient permission to overwrite the existing file on the server.

**Comment by pascalflohr** [comment]
@mradamcox thank you, that is all working well now! At least E24 upload including a relations tab has gone in correctly without problems. Indeed I was using a file that I had validated in the past. I have not yet been able to test a separate relations upload or information resource upload with attached images, will try those soon I hope.

**Comment by michaeltfisher** [comment]
An E27 file and a Relationships file also validated, and so it looks like this particular issue is resolved.

**Comment by pascalflohr** [comment]
And even an information resource one also validated succesfully, so most definitely resolved.
