### ISSUE TITLE
Branch Structure in E24 Condition Assessment Form/Graph

### ISSUE THREAD

**Issue by mradamcox** [azerbini/eamena_dev#17]
The desired structure for the E24 Condition Assessment form includes the following:

**Risk (STEP 2)**
+ Threat and Risk Identification (red below):
    1. Related Vulnerability Factors (Vulnerability_Type.E55)
    1. Exposure (Exposure.E62)
    1. Threat (Threat_Type.E55)
    1. Potential Impact (Potential_Impact_Type.E55)
    1. Secondary Threat (Secondary_Threat_Type.E55)
+ Risk Magnitude Assessment (blue below)
    1. Probability (Threat_Probability_Type.E55)
    1. Extent (Risk_Extent_Type.E55)
    1. Severity (Risk_Severity_Type.E55)
    1. Risk Level (Risk_Level.I4)
    1. Risk Certainty (Risk_Level_Certainty.I6)

However, looking at the E24 graph, these nodes groupings are spread between different branches.
![image](https://user-images.githubusercontent.com/10427268/39815993-7bda26a0-535f-11e8-911a-5cf48ce5cee8.png)
Specifically, the Vulnerability Type and Exposure which are the only nodes in the Treat and Risk Identification that extend from the RISK_PREDICTION_EVALUATION.XX2 node.
Also, note that the RIKS_EVALUATION_ASSESSOR_NAME.E41 [sic] is not included in the list above, though I'm assuming it should just be added to the Risk Magnitude Assessment section.

Ultimately, I'm just not exactly sure how to proceed as I don't think the exclude_empty_branches function would be enough to handle the structure here...

**Comment by azerbini** [comment]
@mradamcox I don't think this will present major issues as all the nodes come off the same main merge node (Potential_state_prediction.xx1). Go ahead to try and implement this as by requirements, then we will troubleshoot if necessary. I think the `exclude_empty_branches` function should work here.

As for the RIKS_EVALUATION_ASSESSOR_NAME node, could you please put together an sql that changes this to RISK_* across the db structure. And yes, you are right, it should be on the interface doc. I have added it now.

**Comment by azerbini** [comment]
@mradamcox actually Adam, you can use a tool in the migrate_resources.py package to rename nodes (I had forgotten that my colleague Andy had developed this). Please pull the latest commits on the eamena-migration-branch then check out this: https://github.com/azerbini/eamena_dev/blob/fdb3d80744490b0c222fdad9cac7a771a5f6e428/arches/management/commands/package_utils/migrate_resources.py#L385

The command to run this is: `python manage.py packages -o rename_entity_type --oldtype OLD_NAME.E55 --newtype NEW_NAME.E55`

**Comment by AzadehVafadari** [comment]
@mradamcox Hi Adam, they **are both part of the same add** (both risk identification and risk magnitude concepts). 
And you are correct, exposure and vulnerability are part of the magnitude assessment process (hence coming from Evaluation.XX2 node.  But in the UI as we are identifying vulnerability and exposure (as oppose to evaluating probability/extent/severity) I categorized them separately.

**Comment by AzadehVafadari** [comment]
bare with me; I'm trying to make a mock up!!!

**Comment by AzadehVafadari** [comment]
[Risk Mock up.pdf](https://github.com/azerbini/eamena_dev/files/1991906/Risk.Mock.up.pdf)

**Comment by AzadehVafadari** [comment]
Not sure how to add/paste an image here. Can you open it?

**Comment by AzadehVafadari** [comment]
If in the UI we change the name "Risk Magnitude Assessment" to "Risk Assessment", then we can include the Exposure and Vulnerability fields:

Threat and Risk Identification 
- Threat (Threat_Type.E55)
- Potential Impact (Potential_Impact_Type.E55)
- Secondary Threat (Secondary_Threat_Type.E55)

Risk Assessment 
- Related Vulnerability Factors (Vulnerability_Type.E55)
- Exposure (Exposure.E62)
- Probability (Threat_Probability_Type.E55)
- Extent (Risk_Extent_Type.E55)
- Severity (Risk_Severity_Type.E55)
- Risk Level (Risk_Level.I4)
- Risk Certainty (Risk_Level_Certainty.I6)

ALL PART OF THE SAME ADD 

Does it make sense? if so I will also update the E24 interface sheet

**Comment by azerbini** [comment]
@AzadehVafadari , I can open the pdf just fine. To display an image ina  comment, just drag&drop a jpg/img/png on the comment box.

Thank you for clarifying how the forms will work. I am sure @mradamcox will be able to take it from here.

**Comment by mradamcox** [comment]
Hey @AzadehVafadari, the mockup clears everything up for me. I thought they were different sections under different "Add" groups. Thanks!

**Comment by mradamcox** [comment]
I'm thinking now that I also have the step 1 wrong too. Should "Damage Overall Severity" and "Damage Overall Extent" be grouped with the "Disturbances" content? I'm thinking yes.
![image](https://user-images.githubusercontent.com/10427268/39892824-7fee7026-5467-11e8-94c5-92a72e674f16.png)

**Comment by azerbini** [comment]
I’ll let Azadeh reply to this, but a quick comment on the 4 dates: they shouldn’t all be visible at the same time, but appear depending on what the Date Type toggle shows. You can take the code for this from condition-assessment.js and condition-assessment.htm.

Sent from my iPhone

On 10 May 2018, at 21:34, mradamcox <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm thinking now that I also have the step 1 wrong too. Should "Damage Overall Severity" and "Damage Overall Extent" be grouped with the "Disturbances" content? I'm thinking yes.
[image]<https://user-images.githubusercontent.com/10427268/39892824-7fee7026-5467-11e8-94c5-92a72e674f16.png>

**Comment by AzadehVafadari** [comment]
@mradamcox No! It is correct!
A note to explain: at E24 level when assessing a feature (site elements, structures, etc) as a whole, different [cause/damage/trend] are identified but then we assess the overall severity and extent of damage for the whole feature. So as you've coded it, separate Adds are needed. 
But for B2, severity and extent should be grouped with cause/damage/trend as at this level we assess them for each identified damage

**Comment by AzadehVafadari** [comment]
@mradamcox can I ask you to change couple of things in Step 1:
can you 
1. change "Cause Category" to just  "Category" (or "Disturbance Category") 
2. change the order as follows: first "Effect/Damage", then "Damage Trend" then we have "Category", "Cause", "Cause Certainty" and "Date" 
(main difference between field and remote assessment: in the remote assessment (E27) usually the assessor knows the cause and the actual damage might (or not) be visible using the imagery. However when we are assessing in the field, we see the damage, but then if we can, have to identify the "invisible" cause!) 
Thanks

**Comment by mradamcox** [comment]
More issues with this form and branch. I believe it stems from the way the graphs are constructed vs. the desired node groupings. The example below is the E24 graph, where DAMAGE_STATE.E3 is the highest node up the graph (right underneath CONDITION_ASSESSMENT.E14) and includes all of the nodes that need to be updated (circled).
![image](https://user-images.githubusercontent.com/10427268/40147629-100c3e0a-5930-11e8-8984-2d257ba9d220.png)
Therefore, DAMAGE_STATE.E3 must be used as the data key in forms.py. However, as you can see, not every node under DAMAGE_STATE.E3 is meant to be included in the add group. This is ok initially, and yields something like this (note the Cause Certainty value here is "Definite", and please disregard all other values)
![image](https://user-images.githubusercontent.com/10427268/40147865-f2745ade-5930-11e8-973f-dec15edfac30.png)
And the relevant portion of the corresponding graph debug structure is like this (note ``"DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Definite"``):
```
            "DAMAGE_STATE_E3": [
                {
                    "orderby": "", 
                    "DISTURBANCE_EVENT_E5": [
                        {
                            "DISTURBANCE_CAUSE_ASSIGNMENT_E13": [
                                {
                                    "orderby": "", 
                                    "DISTURBANCE_CAUSE_BELIEF_I2": [
                                        {
                                            "DISTURBANCE_CAUSE_TYPE_I4": [
                                                {
                                                    "DISTURBANCE_CAUSE_TYPE_I4__label": "Conservation"
                                                }
                                            ], 
                                            "orderby": "", 
                                            "DISTURBANCE_CAUSE_CERTAINTY_I6": [
                                                {
                                                    "DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Definite"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ], 
                            "orderby": "", 
                            "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55": [
                                {
                                    "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55__label": "Funerary/Memorial"
                                }
                            ]
                        }
                    ], 
```
However, if I want to add a second disturbance to the condition assessment, which I assume is desirable, at first it seems like the interface will allow it (I'm only populating the certainty node dropdown here)
![image](https://user-images.githubusercontent.com/10427268/40148061-bfdd8bb2-5931-11e8-8c96-362ff84f0523.png)
But when I save, it looks as though the new disturbance has been mixed with the existing one, note that "Low" is now shown instead of "Definite" and there is only one line.
![image](https://user-images.githubusercontent.com/10427268/40148095-e9ce820a-5931-11e8-8b66-3c96bb8017b0.png)
Finally, in the resource debug graph, we can actually see what's going on
```
            "DAMAGE_STATE_E3": [
                {
                    "orderby": "", 
                    "DISTURBANCE_EVENT_E5": [
                        {
                            "DISTURBANCE_CAUSE_ASSIGNMENT_E13": [
                                {
                                    "orderby": "", 
                                    "DISTURBANCE_CAUSE_BELIEF_I2": [
                                        {
                                            "DISTURBANCE_CAUSE_TYPE_I4": [
                                                {
                                                    "DISTURBANCE_CAUSE_TYPE_I4__label": "Conservation"
                                                }
                                            ], 
                                            "orderby": "", 
                                            "DISTURBANCE_CAUSE_CERTAINTY_I6": [
                                                {
                                                    "DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Definite"
                                                }, 
                                                {
                                                    "DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Low"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ], 
                            "orderby": "", 
                            "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55": [
                                {
                                    "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55__label": "Funerary/Memorial"
                                }
                            ]
                        }
                    ], 
```
"Low" and "Definite" are in the same subsection, and you can see that there is no new DISTURBANCE_EVENT_E5 as there should be.

I'm not sure where to go with this besides breaking the interfance into slightly smaller add groups that more closely represent the branch structure (though I'm not 100% sure that would work). I have been fiddling around for a long time with the merge() and merge_at() functions and just not having any luck with getting the results I need.

**Comment by azerbini** [comment]
Hi Adam, please package your changes to forms.py and the UI in a PR and I will take it from there. Please note I have pushed a commit to forms.py yesterday, so please merge that at your end before pushing.



Sent from my iPhone

On 16 May 2018, at 23:57, mradamcox <notifications@github.com<mailto:notifications@github.com>> wrote:


More issues with this form and branch. I believe it stems from the way the graphs are constructed vs. the desired node groupings. The example below is the E24 graph, where DAMAGE_STATE.E3 is the highest node up the graph (right underneath CONDITION_ASSESSMENT.E14) and includes all of the nodes that need to be updated (circled).
[image]<https://user-images.githubusercontent.com/10427268/40147629-100c3e0a-5930-11e8-8984-2d257ba9d220.png>
Therefore, DAMAGE_STATE.E3 must be used as the data key in forms.py. However, as you can see, not every node under DAMAGE_STATE.E3 is meant to be included in the add group. This is ok initially, and yields something like this (note the Cause Certainty value here is "Definite", and please disregard all other values)
[image]<https://user-images.githubusercontent.com/10427268/40147865-f2745ade-5930-11e8-973f-dec15edfac30.png>
And the relevant portion of the corresponding graph debug structure is like this (note "DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Definite"):

            "DAMAGE_STATE_E3": [
                {
                    "orderby": "",
                    "DISTURBANCE_EVENT_E5": [
                        {
                            "DISTURBANCE_CAUSE_ASSIGNMENT_E13": [
                                {
                                    "orderby": "",
                                    "DISTURBANCE_CAUSE_BELIEF_I2": [
                                        {
                                            "DISTURBANCE_CAUSE_TYPE_I4": [
                                                {
                                                    "DISTURBANCE_CAUSE_TYPE_I4__label": "Conservation"
                                                }
                                            ],
                                            "orderby": "",
                                            "DISTURBANCE_CAUSE_CERTAINTY_I6": [
                                                {
                                                    "DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Definite"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            "orderby": "",
                            "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55": [
                                {
                                    "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55__label": "Funerary/Memorial"
                                }
                            ]
                        }
                    ],


However, if I want to add a second disturbance to the condition assessment, which I assume is desirable, at first it seems like the interface will allow it (I'm only populating the certainty node dropdown here)
[image]<https://user-images.githubusercontent.com/10427268/40148061-bfdd8bb2-5931-11e8-8c96-362ff84f0523.png>
But when I save, it looks as though the new disturbance has been mixed with the existing one, note that "Low" is now shown instead of "Definite" and there is only one line.
[image]<https://user-images.githubusercontent.com/10427268/40148095-e9ce820a-5931-11e8-8b66-3c96bb8017b0.png>
Finally, in the resource debug graph, we can actually see what's going on

            "DAMAGE_STATE_E3": [
                {
                    "orderby": "",
                    "DISTURBANCE_EVENT_E5": [
                        {
                            "DISTURBANCE_CAUSE_ASSIGNMENT_E13": [
                                {
                                    "orderby": "",
                                    "DISTURBANCE_CAUSE_BELIEF_I2": [
                                        {
                                            "DISTURBANCE_CAUSE_TYPE_I4": [
                                                {
                                                    "DISTURBANCE_CAUSE_TYPE_I4__label": "Conservation"
                                                }
                                            ],
                                            "orderby": "",
                                            "DISTURBANCE_CAUSE_CERTAINTY_I6": [
                                                {
                                                    "DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Definite"
                                                },
                                                {
                                                    "DISTURBANCE_CAUSE_CERTAINTY_I6__label": "Low"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            "orderby": "",
                            "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55": [
                                {
                                    "DISTURBANCE_CAUSE_CATEGORY_TYPE_E55__label": "Funerary/Memorial"
                                }
                            ]
                        }
                    ],


"Low" and "Definite" are in the same subsection, and you can see that there is no new DISTURBANCE_EVENT_E5 as there should be.

I'm not sure where to go with this besides breaking the interfance into slightly smaller add groups that more closely represent the branch structure (though I'm not 100% sure that would work). I have been fiddling around for a long time with the merge() and merge_at() functions and just not having any luck with getting the results I need.

**Comment by azerbini** [comment]
00a9ac8 addresses and fixes these issues
