### ISSUE TITLE
Validation of branches must allow nodes to be left empty

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_dev#19]
Not all nodes in a branch will be required. I have pushed a new commit (a9af471) which slightly alters validateHasValues allowing it to accept a second argument, canBeEmpty, an array which contains optional nodes passed at the level of each form's addBranchList(). Please use this validation strategy across the new E24 and B2 forms ( I have applied it to several E27 forms, as the latest commit 3a949b6 shows).

**Comment by mradamcox** [comment]
@azerbini This operation was already available in the new validation tools that I added here https://github.com/azerbini/eamena_dev/pull/6. Once you have instantiated a ValidationTools object in a form's js, you can call it like this https://github.com/azerbini/eamena_dev/pull/6/commits/30cfe8d572e1b84598096a84df04d883247dd589#diff-b5fe86904e943448ddfa9b5b4c63e72dL44.

**Comment by azerbini** [comment]
@mradamcox  Let's speak on the phone cause I don't see anything at line 44 that would work like the new validateHasValues

**Comment by mradamcox** [comment]
Yes, that's just a general example of using the ValidationTools, the function I was referring to is called nodesHaveValues and is described in the body of the pull request. The code for it is here: https://github.com/azerbini/eamena_dev/pull/6/commits/30cfe8d572e1b84598096a84df04d883247dd589#diff-154300c822ad06334623cc3995120d28R70

**Comment by azerbini** [comment]
Ah I see now. We should then remove validateHasValues from branch-lists.js altogether and replace it with your new nodesHaveValues, though of course this would mean changing a ton of other javascripts.

**Comment by mradamcox** [comment]
That makes sense to me.

**Comment by mradamcox** [comment]
It would be good to centralize ALL branch validation functions into validation.js. nodesHaveValues could be slightly modified to accept "all" as an argument which would check all nodes in the branchlist, not just specific ones. Or perhaps that would be the behavior if no nodes to check were passed in.

**Comment by azerbini** [comment]
I think nodesHaveValues needs to look exactly like validateHasValues looks like right now.

**Comment by mradamcox** [comment]
I'm closing this, as our current validation tools do allow for all of this functionality, and I don't think a big validation refactor is going to be a high priority soon.
