### ISSUE TITLE
Create workflow to bulk upload appended files 

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_dev#29]
This enhancement should build on #27  and incorporate a way for people to upload data appended to an E73 Information Resource bulk upload file. At the moment, only the metadata can be bulk uploaded, but not the actual files (imagery, pdfs etc.). 

_Proposal_
An extra step in the Bulk upload view workflow  becomes available if the user selects 'Information Resource' as a resource type, and allows the user to select a folder on their computer containing the appended files. 

A validation tool should then inspect the file names and make sure they that correspond to the names listed in the spreadsheet in a column that we will call 'FILE_NAME' to go in a separate  worksheet named ATTACHMENTS. If the validation is passed, the files are uploaded one by one after the metadata has been.

**Comment by mradamcox** [comment]
Per our discussion last Friday I'm going to remove my assignment to this issue at this time.

**Comment by TeriForey** [comment]
Hi Andrea, just to check: 
1. There would only be one file uploaded per resource
2. We want to create the resources using the server-side archesfile as the bulk_upload currently works
3. We then want to edit each existing resource, adding the local file which is simultaneously uploaded to S3 (plus a thumbnail version). This would essentially use the same process as editing a resource on the resource manager page, and not the JSON/arches file upload that I was working on last time.

Does that sound correct?

**Comment by azerbini** [comment]
Hi Teri,


That is exactly how it should work. Please go ahead with designing this workflow. Please note that all the code for the bulk upload workflow currently resides on the EAMENA-27-bulk-upload-view branch.




________________________________

**Comment by TeriForey** [comment]
Hi Andrea,

As you can see I've added a pull request which should fix this issue. It involves quite a few changes to other processes, including outputing new information from the load_resources command. Most of the javascript works well, the option to select a folder to upload only becomes available if it's an information resource and the validation step sees attached files. Unfortunately the initial excel spreadsheet upload widget runs both upload views and I'm not sure how to stop it from doing that - someone with more javascript experience will probably be able to fix it though!

**Comment by mradamcox** [comment]
@TeriForey I'm going to close this now as I just merged the PR. I didn't see the issue with the upload js, but I'm sure we can fix that down the road. Just wanted to move this along for right now. @azerbini Please reopen this ticket if you'd like to address that before closing.
