### ISSUE TITLE
Proposed Icons for Heritage Place, Heritage Feature, and Heritage Component

### ISSUE THREAD

**Issue by mradamcox** [azerbini/eamena_dev#3]
It's kind of a conceptual approach, but I think this may be a nice way to show the hierarchy and relationship between these features.

![image](https://user-images.githubusercontent.com/10427268/39005858-eb7896c0-43c6-11e8-8d4b-2d71c280d41f.png)

**Comment by mradamcox** [comment]
Note that above I am using `fa-square` for Heritage Place, but I think the better icon would actually be `fa-square-full`. 
![image](https://user-images.githubusercontent.com/10427268/39010061-12cd6cbc-43d3-11e8-9beb-1769cad11f2f.png)
However, this doesn't seem to be available in the version of font awesome that we are currently using, so an upgrade would do well to accompany this ticket.

**Comment by azerbini** [comment]
@mradamcox yes, agreed. Happy to port to the newest version of font-awesome.
