### ISSUE TITLE
Create alert if a resource is created in the same location as a pre-existing resource of the same type

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_dev#38]
https://github.com/azerbini/eamena_v3/issues/96

The point of this enhancement is to make sure that resources of the same type are not duplicated by means of human error (people adding the same thing twice). When a user saves a new resource in a certain location, we would want the app to interrogate the database and make sure that instances of the same resource type do not exist already within the same geometry **or** in a small radius around it. The radius would be variable for settings.py. 

The workflow would be as follows:

Front-end: user saves

Back-end: query to geometries table, within radius. If anything is returned, pass back to the front-end some JSON containing the primaryname of the resources within the radius, and their UUIDs

Front-end: if anything returned, give an alert listing the primarynames as URLs, otherwise just save the resource and carry on.

**Comment by TeriForey** [comment]
Hi Andrea, I just wanted to ask a couple of questions now that I've started making progress on this issue:
1. I presume I should use the eamena_migration_branch as the base?
2. What do you want me to do with the returned JSON? At the moment I'm sending the number of nearby resources to a message.
3. How large a radius are you likely to use? i.e. should it be measured in meters or km?
4. At the moment, I'm querying the database to find any Geometries with a distance to the target less than x Km but it's really quite slow. I'll try to find a faster way of doing this - unless you already know of a faster method?
5. Related to those last two points, it's much quicker to use Dwithin to find geometries within a distance but this requires using degrees to measure the radius and not m/km. Therefore how much error is acceptable?

**Comment by TeriForey** [comment]
Pull request deals with the above questions by:
1. It's based on the eamena-migration-branch
2. It's just printed to the terminal so you can see the results easily to create the alert
3. Measured in meters, then converted to decimal degrees based on the target latitude
4. Using dwithin which is much faster. Process is now slowed down only if a large number of resources are returned (i.e. using a large radius). 
5. Error should be fairly minimal as the distance in degrees is calculated based on the central latitude of the target geometry.

**Comment by azerbini** [comment]
Hi Teri,

1) yes
2) JSON should include: resource primary name and uuid of each resource within the radius. Return the json to the forms.py load method and I will take it from there
3) metres
4) perhaps it would be worth querying the ES index instead as that will be faster.

Sent from my iPhone

On 19 Jul 2018, at 09:05, Teri Forey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Andrea, I just wanted to ask a couple of questions now that I've started making progress on this issue:

  1.  I presume I should use the eamena_migration_branch as the base?
  2.  What do you want me to do with the returned JSON? At the moment I'm sending the number of nearby resources to a message.
  3.  How large a radius are you likely to use? i.e. should it be measured in meters or km?
  4.  At the moment, I'm querying the database to find any Geometries with a distance to the target less than x Km but it's really quite slow. I'll try to find a faster way of doing this - unless you already know of a faster method?

**Comment by TeriForey** [comment]
Hi Andrea, if you want the results passed to the forms.py load method, does that mean you want the function to run every time the form is viewed? I've currently set it up to run during the POST request, after the form.update method and before the resource is saved - would you rather I move it to the GET request view?

**Comment by azerbini** [comment]
@TeriForey , we want the function to run every time a POST request involves the **addition** or  **change** of the inspected node types (in our case, the geometry nodes). When this occurs, and if the query returns results, then the POST should not lead to any saving of new resources, but rather return JSON back to forms load, so that I can take the JSON to populate the alert when the form is reloaded at the end of the POST. Moreover, it should be the case that, in the case a JSON alert is returned, the edits present in the POST request are returned to the forms load method, so that they can be picked up by the view model and repopulate the front end without the user having to re-enter everything, if he/she is certain that the record is not a duplicate.

I can see from your PR that you have gone ahead and used a logic that queries the Django db model. I thought you said it did not perform too well at scale?

**Comment by TeriForey** [comment]
@azerbini Thank you, I think I follow what you'd like me to do. I'll have another go and update the PR. 

I was originally using `distance_lte` to find nearby resources but that took ~21 seconds to search through the 324000 Geometry models in my database. Using `dwithin` takes ~0.07 seconds, which is what I have in the PR.

**Comment by TeriForey** [comment]
@azerbini I've updated the PR. There are now two new items passed to the form when it's reloaded, `alert` which contains the JSON information on nearby/preexisting resources and `submitted_data` which contains the originally submitted changes that were not saved to the resource.

**Comment by azerbini** [comment]
Hi @TeriForey , please see comments to #42 as the code in #39 is not currently working as expected.
