### ISSUE TITLE
Few mainly text/wording changes in the UI - as a result of a meeting with EAMENA team 

### ISSUE THREAD

**Issue by AzadehVafadari** [azerbini/eamena_dev#41]
Based on the meeting with the team (to finalize the vocabulary and drop-down lists), the following points were identified as mainly texts that need to be changed/altered in the UI:

1.  In all tabs, change _"on behalf of"_ to "_**identified by"**_; team felt that "on behalf of" might be a bit misleading. by using "identified by" it will make it clearer that the xx assessment was identified and done by y person.  

2.  In Feature resource, condition assessment tab
         2.a) in part 1, change _"Damage Overall Severity"_ to **_"Overall Condition / Damage Severity"_**
         2.b) in part 3, change _"Overall Condition"_ to _**"Overall State"**_ 

3.  In Feature resource, condition assessment tab, part 3, change _"Overall Priority"_ to _**"Overall Priority to Implement Actions"**_

4.  for E24/Feature change the term "resource" used in the UI to "Feature. e.g. change "Resource Summary" to "Feature Summary", "Resource Name" to Feature Name", "Heritage Classification" to "Feature Classification", etc. 

5.  It was decided that for EAMENA database there is no need to classify "Features" for now. But since it might be used at a later stage and/or it will be used at in-country implementation, add a more field options at the bottom of the Feature Summary window and move the "Feature Classification" under "More fields" to be hidden for now and only be used when it's needed. 

6. this one is a different type of request/question: would it be possible at this stage of the development to add "risk assessment" to Place/E27?? when we were designing the graph there was no request to add risk assessment to "Place" level and the emphasize was to keep the E27 v.2 workflow as similar to the v.1 workflow as possible. However the team is now showing interest in using detailed risk assessment for Heritage Place as well...

Thanks and let me know if anything is not clear.

**Comment by azerbini** [comment]
@AzadehVafadari I have now addressed all of these except for point 6. Adding risk requires changes to the resource graph, something we are unable to do at this stage of development. We should put this on the backburner until we move to v4.

**Comment by AzadehVafadari** [comment]
Thanks. Makes sense.
