### ISSUE TITLE
Add UTM support to coordinate selector in Location tab

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_dev#45]
![screen shot 2018-09-14 at 11 32 18](https://user-images.githubusercontent.com/19243127/45545380-fd64da00-b811-11e8-9164-25efd9164239.png)

Add a CRS dropdown switch to coordinate selector on Location tab which allows the user to select either decimal degrees or UTM.

**Comment by mradamcox** [comment]
https://github.com/azerbini/eamena_dev/commit/b42f2c1eacd9033b3638ab4510804c3ed6742c8d

**Comment by mradamcox** [comment]
![image](https://user-images.githubusercontent.com/10427268/46364933-d0e7f500-c63c-11e8-8e2f-d109869a6b1e.png)
This has been deployed to the Al Ula server.

**Comment by pascalflohr** [comment]
This is working very well. Is it also possible to have this added to the E24 wizard?
![screen shot 2018-10-20 at 14 46 40](https://user-images.githubusercontent.com/43570914/47255275-fcf5d980-d476-11e8-8f64-0fd9c2b97ce6.png)

(but lower priority at the moment I think)

**Comment by mradamcox** [comment]
Ok, I'm going to close this ticket because #66 captures the above comment.
