### ISSUE TITLE
Numbering sequence of rows in bulk upload validation is incorrect

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#52]
@mradamcox 
### Bug Report
Bulk upload validation returns the right error but refers to the wrong row and column.

![](https://files.slack.com/files-pri/T8CLY0DML-FD1GXN70U/screen_shot_2018-09-26_at_19.56.26.png)
<img width="674" alt="screen shot 2018-09-26 at 19 56 26" src="https://user-images.githubusercontent.com/43570914/46140231-69026a80-c248-11e8-8380-8e7702858d69.png">

In the screenshot attached, the correct row was 68 with column 2.

#### Your Arches Information

* Version used: Al Ula v2
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mac OS X Yosemite
* Link to your Arches Install (optional):

**Comment by pascalflohr** [comment]
Also the case in FeatureGroup and InterprGroup, actual row is 2 down (so when row 36 is indicated, the error is actually present in row 38).

**Comment by mradamcox** [comment]
@pascalflohr new output:
![image](https://user-images.githubusercontent.com/10427268/46224679-a6d0c300-c31c-11e8-99c1-7270f03ed29d.png)
not deployed yet but will be soon.
