### ISSUE TITLE
Bulk upload: Concept fail is not flagged up until arches file writing

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#53]
### Bug Report
The EFFECT_TYPE.I4 concept "Collapse/Structural Damage" was written wrong as "Structural Damage/Collapse". However the file got through the validation process and this was only flagged up in the write_arches_file stage (screenshot).

<img width="576" alt="screen shot 2018-09-28 at 10 41 31" src="https://user-images.githubusercontent.com/43570914/46201333-c01d4380-c30b-11e8-912e-817c1e6a0000.png">

#### Expected Behavior
Should be flagged up in the concept validation phase.

#### Current Behavior
Not flagged up in concept validation phase, instead flagged up in write_arches_file phase.

**Comment by mradamcox** [comment]
This is now fixed. Originally the validation was not recognizing multiple columns with the same name.
