### ISSUE TITLE
Bulk upload - number "1" shown as "unknown"

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#63]
### Bug Report
When the interpretation number is "1" in the bulk upload file, it is shown as "Unknown" in the database. 

Like in this example:

<img width="823" alt="screen shot 2018-10-11 at 10 08 59" src="https://user-images.githubusercontent.com/43570914/46786501-bc42e580-cd3d-11e8-8078-d84f92e15eea.png">

**Comment by mradamcox** [comment]
https://github.com/azerbini/eamena_dev/commit/820659f50d8f5914775eb3fa53a5b8e75f6476d1 fixes this. Thanks @azerbini for the tip on where the issue was. The change is deployed to the staging server, @pascalflohr could you test and close this issue when you can confirm the fix? Thanks.

**Comment by pascalflohr** [comment]
The bulk uploads were unloaded and partly reloaded by @azerbini and the interpretation numbers 1 have gone is OK now.
