### ISSUE TITLE
Order of Function Type and Function Type Certainty

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#64]
Once entered, Function Type and Function Type Certainty are shown in the wrong order. Function Type should come first, followed by Function Type Certainty, as this is more clear.

<img width="823" alt="screen shot 2018-10-11 at 10 08 59" src="https://user-images.githubusercontent.com/43570914/46786629-1f347c80-cd3e-11e8-9289-d756a17e1fdf.png">

**Comment by mradamcox** [comment]
Hi @pascalflohr, I'm trying this out in the E27 Archaeological Assessment form, and it looks like the order is correct:
![image](https://user-images.githubusercontent.com/10427268/46907146-d0205000-ced3-11e8-90ed-7b6779438573.png)
Is there somewhere else I should look for this error?

**Comment by pascalflohr** [comment]
Hi @mradamcox, in that case it seems that the wrong order only occurred when the data came in through a bulk upload. Is there a way to correct this?

**Comment by mradamcox** [comment]
Ah, ok, I think I see what's going on. @azerbini I'm guessing that this has to do with the multiple columns with the same name situation we discussed. It seems as though certainty is in the first group, and type is in the second, like this (the red scribbles indicating filled in attributes):
![image](https://user-images.githubusercontent.com/10427268/47043142-809b8780-d152-11e8-9947-36da1ab687ef.png)
@pascalflohr would you be able to pass along the excel file (or an excerpt from it) that produced these results?

**Comment by pascalflohr** [comment]
[E27_Al Ula 3726-31 - AS SUDAYD_cleaned.xlsx](https://github.com/azerbini/eamena_dev/files/2488046/E27_Al.Ula.3726-31.-.AS.SUDAYD_cleaned.xlsx)

@mradamcox for example this one

**Comment by mradamcox** [comment]
@pascalflohr and @azerbini, after testing with Pascal's excel file I realized I was wrong in my initial theory. Turns out that the resource itself is correctly constructed, but the nodes that are iterated during this display process are not passed to the template in the same order every time. I fixed it with separate iterations that look for each node in turn.
