### ISSUE TITLE
E24 Feature Morphology/Form 'Add' button does not work

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#67]
When pressing the 'Add' button for the E24 Feature morphology fields, nothing happens.

<img width="759" alt="screen shot 2018-10-16 at 17 44 59" src="https://user-images.githubusercontent.com/43570914/47024950-599d7f80-d16b-11e8-80b3-555d03606fe2.png">

**Comment by pascalflohr** [comment]
@mradamcox because of this, currently unable to add the Archaeological Assessment to any of the E24s (except I assume through bulk upload)

**Comment by pascalflohr** [comment]
Actually, John has now managed to do this - not sure when it does and doesn't work, or perhaps it got fixed in the meantime. Will test further.

**Comment by mradamcox** [comment]
@pascalflohr When I'm testing this locally, it seems like it works when I add the "Identified By" attribute (click on the pencil, then enter a name). I _believe_ that is the desired validation (that everything be filled out) but a red error message should show up, like normal.

**Comment by pascalflohr** [comment]
@mradamcox thanks for that - I think it should work like in the E27, that "identified by" is assigned automatically to logged in person unless specifically entered differently

**Comment by mradamcox** [comment]
Ok, sounds good. The fixes are applied for this, so you can test it out.

**Comment by pascalflohr** [comment]
This is working now, thanks!
