### ISSUE TITLE
unable to upload images

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#69]
When uploading images, either directly in the Information Resource or in the Heritage Resource, the image is not uploaded. When doing this in the Heritage Resource, no information resource is produced at all.

**Comment by pascalflohr** [comment]
This is in the Al Ula database - quite high priority for me, as I am currently training people in this

**Comment by pascalflohr** [comment]
There also seems a problem with indexing, it seems not possible to find back information resources that have been made, the search shows 0. I am in the middle of giving training so cannot check what the problem is exactly - @mradamcox could you look into this as Andrea is on holiday?

**Comment by pascalflohr** [comment]
I have looked into this issue more. Creating an information resource from scratch via Resource Manager - Information Resource is fine and the record can be found back and edited etc., until an image (or presumably any attachment) is added. This does not work, the image is being loaded, a red cross appears, and the screen goes back to what it was like before, without any image showing. After this, the record then does not show up in the search anymore, although the number exist:

<img width="902" alt="screen shot 2018-10-18 at 14 30 14" src="https://user-images.githubusercontent.com/43570914/47151479-8fb13f80-d2e2-11e8-920b-341cc00d1978.png">

<img width="908" alt="screen shot 2018-10-18 at 14 26 44" src="https://user-images.githubusercontent.com/43570914/47151531-af486800-d2e2-11e8-9efc-ea5951cf2feb.png">

<img width="1128" alt="screen shot 2018-10-18 at 14 27 12" src="https://user-images.githubusercontent.com/43570914/47151538-b53e4900-d2e2-11e8-8e8a-2f9ff83f551e.png">

A similar thing happens when attaching an image through the wizard menu in an Heritage Resource, although I am not sure if an Information Record is created at all in that case (but I think it is).

**Comment by mradamcox** [comment]
Ok, I found a setting that was not configured correctly for file uploading and updated it. @pascalflohr could you test again?

**Comment by pascalflohr** [comment]
Thanks - I have now also been able to add a file to the record without problems, great!

Is there a way to get to those five 'lost' records and edit or delete them? (INFORMATION-0000001 to 5).

When I click on the Information resource in the search I get the following, but I think that must just be the report page not being ready yet, so a different issue (and for now we can go directly to edit):
<img width="1209" alt="screen shot 2018-10-18 at 18 26 03" src="https://user-images.githubusercontent.com/43570914/47165782-71a80700-d303-11e8-857c-4cd997429de1.png">

**Comment by mradamcox** [comment]
@pascalflohr I'll see what I can do about deleting these resources. You're correct that the report template is just not ready yet, and that's causing the error above.

**Comment by mradamcox** [comment]
@pascalflohr I have reindexed the database, and it seems to have solved this issue of the leftover resources:

![image](https://user-images.githubusercontent.com/10427268/48089704-b7514480-e1ca-11e8-8273-e5eb32e25c2f.png)

I'm going to close this ticket (the original issue has been addressed), so if you still find issues along these lines, please open up a new ticket.
