### ISSUE TITLE
Request: open Heritage Feature in new window

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#75]
In the E27 Heritage Place - Related Heritage Features tab, an overview is given of the related heritage features and one can click on these to navigate to the E24 Heritage Feature record. Could this please automatically open in a new window? 

![screen shot 2018-10-20 at 14 47 51](https://user-images.githubusercontent.com/43570914/47287590-71f21c00-d5fb-11e8-80e6-8d80b23dbb0c.png)

**Comment by mradamcox** [comment]
@pascalflohr could you check this out and close if it's satisfactory? I made the same change to the E24 component wizard for the sake of consistency.
