### ISSUE TITLE
Location duplicate warning buffer too large

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#76]
The location duplicate warning each time a geometry is added to a record is working and very useful, but is currently indicating too many sites over a large area. Could the distance between the geometry to be added and the potential duplicates be made smaller?

Not sure what it is set at now? We are thinking 50m diameter would be good, but it might be a bit of trial and error.

**Comment by mradamcox** [comment]
@pascalflohr, it looks like it is set at 1km right now https://github.com/azerbini/eamena_dev/blob/alula-stable/eamena/eamena/settings.py#L280. I will change this to 50m for now, and let me know in a few days if you want it changed again. It's a very simple thing to update, but I'll have to do it from my end at this point.

**Comment by mradamcox** [comment]
@pascalflohr have you been able to test this out yet?

**Comment by pascalflohr** [comment]
@mradamcox yes and it looks good now, fewer duplicate warnings coming up for each site so now restricted to the relevant ones only
