### ISSUE TITLE
More fields to be made mandatory again

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#77]
Several fields that were mandatory in v1 are not mandatory anymore in v2 (at least for Al Ula), but should be:
- [x] Location Certainty (E27 and E24)
- [x] Overall Site Shape (E27 only)
- [x] Certainty of Geometric Extent (E27 only)
- [x] Topography (E27 only)
- [x] Disturbance Effect 1 & Disturbance Effect 1 Certainty (not sure which number these fields currently have in the RDM, as there are many now - basically the first disturbance effect)
- [x] Disturbance Date Type & Disturbance Date

**Comment by mradamcox** [comment]
I was unable to figure out how to make an error get thrown if a point is added without a Location Certainty attribute, because of the underlying way those nodes are included in this form. @azerbini do you have any thoughts on how to accomplish this?

**Comment by mradamcox** [comment]
@pascalflohr could you check all of the ones that I completed to make sure every thing is ok? You'll likely need to do a "hard refresh" of your browser, so that some of the javascript logic files update correctly. Use ctrl + F5.

**Comment by azerbini** [comment]
@mradamcox I am working on this ticket, should have a commit ready soon for Location Certainty

**Comment by mradamcox** [comment]
I have tested this and it works as desired. Thanks @azerbini!
