### ISSUE TITLE
Request: showing more search results per page

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#82]
This is not a high priority, but for the Al Ula database, could more (e.g. 20) results per page be shown for the search results, like in the EAMENA database? Currently only 5 are shown.

<img width="931" alt="screen shot 2018-11-18 at 17 24 10" src="https://user-images.githubusercontent.com/43570914/48673854-eb2b5300-eb56-11e8-90b7-43072346bf1b.png">

**Comment by mradamcox** [comment]
@pascalflohr I have fixed this. There was an issue with how the settings were being imported to configure the app, once I fixed that, the standard of 20 (for EAMENA) kicked in.

**Comment by pascalflohr** [comment]
excellent
