### ISSUE TITLE
Not possible to remove Information Resource Additional Information

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#85]
In an Information Resource, it currently does not appear possible to remove or edit an added "Additional Information" text once this has been entered. 

In the screenshot, I would like to remove the Arabic text. The text might have been added when creating the information resource from a Heritage Place E27 record, but currently the Information Resource is not showing Related Resources.

<img width="1166" alt="screen shot 2018-11-20 at 14 45 10" src="https://user-images.githubusercontent.com/43570914/48771791-5437d580-ecd3-11e8-9aab-651a9732fb6f.png">

**Comment by azerbini** [comment]
Closing this as it has been addressed @pascalflohr
