### ISSUE TITLE
Read and Edit user groups do not have access to Map View

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#88]
Currently the read, edit, and I think even Edit-plus user groups do not have access to the Map View. To access this it seems Superuser status is needed, or the permission can be assigned individually.

Can Map View be added to all the groups?

**Comment by azerbini** [comment]
This has now been taken care of. Pls remove superuser status to all but the administrators. @pascalflohr

**Comment by pascalflohr** [comment]
thanks! will do
