### ISSUE TITLE
Bulk upload - missing geometries not flagged up during validation

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#90]
When validating bulk uploads (at least for E24 feature) two missing lines of geometry were not flagged up.

**Comment by pascalflohr** [comment]
In the Al Ula database, but presumably the same in EAMENA v2

**Comment by mradamcox** [comment]
@pascalflohr could you be more specific about missing? One big drawback of the bulk upload validation is that it does not check for fields that are "required" through the input forms. So that could be related to what you're seeing with the geometry (or not!). Just wanted to check that first...

**Comment by pascalflohr** [comment]
@mradamcox yes that could be it. It is when the complete line is missing. I had understood that we should always put 'x'es as placeholders, so that other values cannot shift into these places. If this is not flagged up, people might miss this. In this case, would the geometries of line 51 shift to other records, or would the geometries simply be empty? In the latter case it is not such a problem, in the former it would be.

![screen shot 2019-01-15 at 15 10 20](https://user-images.githubusercontent.com/43570914/51189436-fa6d1980-18d7-11e9-8531-03c64fd62941.png)

**Comment by mradamcox** [comment]
@pascalflohr yes, I see now, indeed I think this empty cells should have been caught. I'll look into it. Thanks for the screenshot.

**Comment by mradamcox** [comment]
@pascalflohr I have pushed a fix to the al-ula server which will hopefully address this. Can you please test it whenever you get a chance? thanks!

**Comment by pascalflohr** [comment]
@mradamcox the bulk upload validation now seems to get stuck after testing the headers:

<img width="1123" alt="screen shot 2019-01-15 at 21 53 09" src="https://user-images.githubusercontent.com/43570914/51212303-1096cc00-1910-11e9-9289-7f88a4261889.png">

not going further after this

**Comment by pascalflohr** [comment]
@mradamcox any news on this? Would it be possible to set it back to the previous state please, as we cannot validate or load at the moment?

**Comment by mradamcox** [comment]
Ok, I think I have the right fix now. Sorry about the delay.

**Comment by pascalflohr** [comment]
excellent news, many thanks!

**Comment by pascalflohr** [comment]
@mradamcox unfortunately my bulk upload still does not seem to get through, it checks the headers, but afterwards the wheel just keeps spinning without anything happening.

**Comment by mradamcox** [comment]
hm, would you be able to send me the file you are trying to upload? e-mail or attaching here, whatever works for you.

**Comment by pascalflohr** [comment]
here is one

same problem for E27s and with several different files

**Comment by mradamcox** [comment]
Ah, it has to do with arabic characters that I didn't have in my test file I was using locally. Sorry about that. I'll post a fix soon.

**Comment by mradamcox** [comment]
Fix applied.

**Comment by pascalflohr** [comment]
excellent, that is all working again and blanks are being flagged up. Thank you @mradamcox!
