### ISSUE TITLE
Finds fields - Assessment type

### ISSUE THREAD

**Issue by pascalflohr** [azerbini/eamena_dev#91]
In Finds - Assessment Summary, the Assessment Type field is currently linked to "Type of Activity" but it should be linked to "Assessment Type" (ASSESSMENT_ACTIVITY_TYPE.E55)..

current situation:
<img width="838" alt="screen shot 2019-01-16 at 12 31 45" src="https://user-images.githubusercontent.com/43570914/51249391-0665e380-198b-11e9-8463-80c9c5c6d6fc.png">

should link to:
<img width="1184" alt="screen shot 2019-01-16 at 12 35 39" src="https://user-images.githubusercontent.com/43570914/51249468-4036ea00-198b-11e9-9a94-94dd801b0c7d.png">

**Comment by pascalflohr** [comment]
This is still outstanding - the level cannot be used without this issue solved...

**Comment by pascalflohr** [comment]
@mradamcox is this something you could fix or should I run this through @michaeltfisher?

**Comment by michaeltfisher** [comment]
I can probably get to this later today.

**Comment by mradamcox** [comment]
@pascalflohr I'm pretty sure this has been fixed, right?

**Comment by pascalflohr** [comment]
@mradamcox that is right, @michaeltfisher has fixed this
